language: c
compiler: gcc

branches:
  only:
    - master
    
env:
  global:
    - secure: "SqwJVkmQ/hf3/Y4JLSdSwE2nxIT7Vyuj3BBRdIDcsOgG5LLfreRbpnFYIAuC\nQ4OPgmBHy2D/BUg9FWQTJ8f5HZ5V0qlBf7yyv8sdATV3USY71MGsoPXviHwK\na7HljM5hWVnPFy8ZhAzXem6F8+pZaftNYGZQgJEYCHKTJyoWP4k="

script:
 - sudo apt-get install mkisofs
 - sudo apt-get install syslinux
 - cd src
 - make
 
after_success:
 - ls -la
 - cd bin
 - ls -la
 - git branch
 - git status
 - cd ..
 - cd ..
 - ./checkin.sh
 
 
