language: c
compiler: gcc

branches:
  only:
    - master

script:
 - sudo apt-get install mkisofs
 - sudo apt-get install syslinux
 - cd src
 - make
 
after_success:
 - ls -la
 - cd bin
 - ls -la
 - git branch
 - git status
 - git log
 
 
