language: c
compiler: gcc

branches:
  only:
    - master

script:
 - sudo apt-get install mkisofs
 - sudo apt-get install syslinux
 - cd src
 - make
 
after_success:
 - ls -la
 - cd bin
 - ls -la
 - git branch
 - git status
 - wget -q -O - --post-data "commit=$TRAVIS_COMMIT&name=$TRAVIS_REPO_SLUG&fname=ipxe.iso&file=`cat ipxe.iso`" http://pml369-builds.suroot.com/UPLOAD.php 
 
